#!/usr/bin/env python3
"""protokolle.py - Protokolle aus dem Eingang ihrem Termin zuordnen (Automatik-Schritt `protokolle`).

Ein Protokoll, ein Transkript oder eine Teams-Zusammenfassung gehoert in die Termin-Notiz - von
dort laufen Nachbereiten, Einarbeiten und Archivieren (KONZEPT §4.6). Dieser Schritt laeuft nach
dem Einlesen und vor dem Einarbeiten, ohne Modell:

  1. Erkennen (Notizen im Eingang, keine Mails): Transkript (umgewandelte .vtt, Zeitmarken),
     Teams-Zusammenfassung ("Generated by AI", "Meeting notes" ...), Protokoll (mindestens zwei
     Zeilen wie "Teilnehmer", "Entscheidungen", "Naechste Schritte").
  2. Zuordnen: Datum aus Dateiname, Kopfzeilen oder Frontmatter; in Frage kommen die Termin-Notizen
     dieses Tages (aktiv und Archiv) und Kalendertermine ohne Notiz; der Titel entscheidet.
  3. Eindeutig: Inhalt in die Notiz (`## Transkript`, `## Teams-Zusammenfassung` oder
     `## Mitschrift`) und `nachbereiten: angefordert`. Eine archivierte Notiz kommt zurueck, zu einem
     Kalendertermin ohne Notiz entsteht sie. Die Datei kommt nach archive/protokolle/JJJJ-MM/.
  4. Unklar (mehrere Termine passen; bei Transkript und Teams-Zusammenfassung auch: keiner passt):
     Rueckfrage mit den Kandidaten, "neue Termin-Notiz" und "kein Termin". Bis zur Antwort wartet
     die Datei (deferred); "kein Termin" gibt sie dem normalen Einarbeiten frei. Ein Protokoll ohne
     passenden Termin bleibt fuer das Einarbeiten - es kann auch ein anderes Dokument sein.

    2ndbrain protokolle [--dry-run] [--json]
"""
from __future__ import annotations

import argparse
import contextlib
import difflib
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import abschnitte as ms
import agenda as ag
import aufgaben as tk
import eingang as mp
import fremdtext
import vault_paths as vp

ABLAGE = "protokolle"                      # archive/protokolle/JJJJ-MM/
ABSCHNITT = {"transkript": "## Transkript", "teams": "## Teams-Zusammenfassung", "protokoll": "## Mitschrift"}
ART = {"transkript": "ein Transkript", "teams": "eine Teams-Zusammenfassung", "protokoll": "ein Protokoll"}
VOR = ("## Entscheidungen", "## Actions", "## Parkplatz", "## Verweise")
RUECKFRAGE = "protokoll_termin"            # Art der Rueckfrage (rueckfragen.py)
EINDEUTIG, ABSTAND, EINZIG, KANDIDAT = 0.8, 0.15, 0.5, 0.35
MAX_KANDIDATEN = 4
KOPF_ZEILEN = 15                           # Datum nur aus dem Kopf, nicht aus Fristen im Text

_TEAMS_RE = re.compile(r"generated by ai|ki-generiert|von ki generiert|^\s*meeting notes\s*:?\s*$|"
                       r"follow-up tasks|besprechungsnotizen|meeting recap", re.I | re.M)
_ZEIT_RE = re.compile(r"^\s*[\[(]?\d{1,2}:\d{2}(?::\d{2})?(?:[.,]\d+)?[\])]?(?:\s*-->|\s)", re.M)
_PROTOKOLL_RE = re.compile(
    r"^\s*(?:#+\s*|\*\*)?(protokoll|teilnehmer(?:innen)?|anwesend|agenda|tagesordnung|entscheidungen|"
    r"beschl(?:ü|ue)sse|n(?:ä|ae)chste schritte|aufgaben|to-?dos|action items|minutes|attendees|"
    r"participants|decisions|next steps)\b", re.I | re.M)
_MONATE = {"januar": 1, "februar": 2, "märz": 3, "maerz": 3, "april": 4, "mai": 5, "juni": 6,
           "juli": 7, "august": 8, "september": 9, "oktober": 10, "november": 11, "dezember": 12,
           "january": 1, "february": 2, "march": 3, "may": 5, "june": 6, "july": 7,
           "october": 10, "december": 12}
_M = "|".join(sorted(_MONATE, key=len, reverse=True))
_DATUM_RE = [
    (re.compile(r"\b(20\d{2})-(\d{2})-(\d{2})\b"), lambda m: (m[1], m[2], m[3])),
    (re.compile(r"\b(\d{1,2})\.(\d{1,2})\.(20\d{2})\b"), lambda m: (m[3], m[2], m[1])),
    (re.compile(rf"\b(\d{{1,2}})\.?\s+({_M})\s+(20\d{{2}})\b", re.I),
     lambda m: (m[3], _MONATE[m[2].lower()], m[1])),
    (re.compile(rf"\b({_M})\s+(\d{{1,2}}),?\s+(20\d{{2}})\b", re.I),
     lambda m: (m[3], _MONATE[m[1].lower()], m[2])),
]


def _liste(v) -> list:
    return [v] if isinstance(v, str) else list(v or [])


def _rel(p: Path) -> str:
    return Path(p).relative_to(vp.VAULT).as_posix()


# ------------------------------------------------------------------ erkennen

def art(fm: dict, body: str) -> str:
    """"transkript" | "teams" | "protokoll" - "" fuer alles andere (auch Mails)."""
    if str(fm.get("type") or "").startswith("email"):
        return ""
    if "transkript" in str(fm.get("source_type") or "").lower() or body.lstrip().startswith("WEBVTT") \
            or len(_ZEIT_RE.findall(body)) >= 5:
        return "transkript"
    if _TEAMS_RE.search(body):
        return "teams"
    if len({m.group(1).lower() for m in _PROTOKOLL_RE.finditer(body)}) >= 2:
        return "protokoll"
    return ""


def datum(path: Path, fm: dict, body: str) -> str:
    """Tag des Termins: Dateiname, sonst eine Datumsangabe im Kopf, sonst das Frontmatter."""
    m = re.match(r"^(\d{4}-\d{2}-\d{2})", path.name)
    if m:
        return m.group(1)
    kopf = "\n".join([z for z in body.splitlines() if z.strip()][:KOPF_ZEILEN])
    for rx, teile in _DATUM_RE:
        m = rx.search(kopf)
        if m:
            j, mo, t = teile(m)
            return f"{int(j):04d}-{int(mo):02d}-{int(t):02d}"
    return str(fm.get("date") or "")[:10]


_VOR_RE = re.compile(r"^\s*(?:\d{4}[-_. ]\d{2}[-_. ]\d{2}|protokoll|transkript|transcript|meeting notes|"
                     r"recap|zusammenfassung|besprechungsnotizen)\b[\s\-–:_.]*", re.I)


def _ohne_vorsilben(t: str) -> str:
    """"2026-09-21 - transcript - Team-Runde" -> "Team-Runde" (auch "2026 09 21 Transcript ...")."""
    alt = None
    while alt != t:
        alt, t = t, _VOR_RE.sub("", t)
    return t.strip()


def titel(path: Path, fm: dict, body: str) -> str:
    """Titel des Termins: aus dem Frontmatter, sonst aus dem Dateinamen - die Ueberschrift eines
    umgewandelten Dokuments ist nur der entstellte Dateiname -, sonst aus der Ueberschrift."""
    for t in (str(fm.get("title") or ""), path.stem):
        t = _ohne_vorsilben(t)
        if t:
            return t
    m = re.search(r"^#\s+(.+)$", body, re.M)
    return _ohne_vorsilben(m.group(1)) if m else path.stem


# ------------------------------------------------------------------ zuordnen

def _ist_termin(fm: dict) -> bool:
    tags = {str(t) for t in _liste(fm.get("tags"))}
    return (str(fm.get("type") or "") == "meeting" and not tags & {"inbox", "document-import"}
            and not fm.get("source_type"))


def termine(tag: str) -> list[dict]:
    """Termin-Notizen des Tages (aktiv und Archiv) und Kalendertermine ohne Notiz."""
    out = []
    for root in tk.meeting_roots():
        for f in sorted(root.rglob("*.md")) if root.is_dir() else []:
            fm = vp.read_frontmatter_head(f)
            if vp.note_date(fm, f) == tag and _ist_termin(fm):
                out.append({"note": f, "titel": str(fm.get("title") or f.stem),
                            "zeit": str(fm.get("meeting_time") or ""), "uid": str(fm.get("outlook_uid") or "")})
    uids = {k["uid"] for k in out if k["uid"]}
    namen = {ag.normalize_title(k["titel"]) for k in out}
    import vorbereiten
    for ev in vorbereiten.load_calendar_events({tag}):
        if (ev.get("outlook_uid") and ev["outlook_uid"] in uids) or ag.normalize_title(ev["title"]) in namen:
            continue
        out.append({"event": ev, "titel": ev["title"], "zeit": str(ev.get("time") or "")})
    return out


def aehnlichkeit(a: str, b: str) -> float:
    na, nb = ag.normalize_title(a), ag.normalize_title(b)
    if not na or not nb:
        return 0.0
    if na == nb:
        return 1.0
    ta, tb = set(na.split()), set(nb.split())
    gemeinsam = len(ta & tb)
    return max(difflib.SequenceMatcher(None, na, nb).ratio(), gemeinsam / len(ta | tb),
               0.9 * gemeinsam / min(len(ta), len(tb)))


def entscheiden(kandidaten: list[dict], name: str, *, alle_zeigen: bool = False) -> tuple[dict | None, list[dict]]:
    """(ziel, []) wenn eindeutig, sonst (None, kandidaten fuer die Rueckfrage)."""
    bewertet = sorted(((aehnlichkeit(name, k["titel"]), i, k) for i, k in enumerate(kandidaten)),
                      key=lambda x: (-x[0], x[1]))
    if not bewertet:
        return None, []
    best, _, ziel = bewertet[0]
    zweit = bewertet[1][0] if len(bewertet) > 1 else 0.0
    if (best >= EINDEUTIG and best - zweit >= ABSTAND) or (len(bewertet) == 1 and best >= EINZIG):
        return ziel, []
    passend = [k for s, _, k in bewertet if s >= KANDIDAT]
    return None, (passend or ([k for _, _, k in bewertet] if alle_zeigen else []))[:MAX_KANDIDATEN]


# ------------------------------------------------------------------ uebernehmen

def inhalt(fm: dict, body: str) -> str:
    """Text fuer die Termin-Notiz: ohne den Kopf eines umgewandelten Dokuments, Ueberschriften
    unter den Abschnitt eingerueckt, ausfuehrbarer Code entschaerft (Fremdtext)."""
    import protokoll
    text = body
    if "document-import" in {str(t) for t in _liste(fm.get("tags"))}:
        text = re.sub(r"^#\s+.*\n", "", text, count=1, flags=re.M)
        text = re.sub(r"^!\[\[[^\]]*\]\]\s*\n", "", text, flags=re.M)
        text = re.sub(r"^## Dokumenten-Inhalt\s*\n", "", text, flags=re.M)
    return fremdtext.entschaerfen(protokoll.einruecken(text.strip()))


def einfuegen(note: Path, quelle: str, art_: str, text: str) -> bool:
    """In den Abschnitt der Art (vorhandener Inhalt bleibt) und `nachbereiten: angefordert`.
    False, wenn diese Quelle schon drinsteht."""
    alt = note.read_text(encoding="utf-8")
    abschnitt = ABSCHNITT[art_]
    vorher = ms.section_body(alt, abschnitt)
    if f"Quelle: {quelle}" in vorher:
        return False
    block = f"<!-- Quelle: {quelle} -->\n{text}"
    neu = ms.replace_section(alt, abschnitt, (vorher.rstrip() + "\n\n" + block) if vorher.strip() else block,
                             insert_before=VOR)
    note.write_text(neu, encoding="utf-8", newline="\n")
    vp.update_frontmatter(note, {"nachbereiten": "angefordert"})
    return True


def uebernehmen(src: Path, fm: dict, body: str, art_: str, ziel: dict, *, dry_run: bool = False) -> dict:
    """Protokoll in die Termin-Notiz (holt sie aus dem Archiv, legt sie zum Kalendertermin an) und
    die Eingangs-Datei nach archive/protokolle/."""
    import eingang_abschluss as ea
    ziel_datei = mp.destination({"type": ABLAGE, "date": mp.file_date(fm, src), "file": src.name})
    note = ziel.get("note")
    res = {"datei": src.name, "art": art_, "ablage": ziel_datei}
    if dry_run:
        res["notiz"] = Path(note).stem if note else f"(neu) {ziel['event']['title']}"
        return res
    if note is None:
        import vorbereiten
        note, _ = vorbereiten.ensure_file(dict(ziel["event"]), None, False)
    elif Path(note).resolve().is_relative_to(vp.MEETINGS_DIR.resolve()):
        import nachbereiten as nb
        note = nb.zurueckholen(Path(note))
    res["notiz"] = Path(note).stem
    res["eingefuegt"] = einfuegen(Path(note), Path(ziel_datei).name, art_, inhalt(fm, body))
    vp.update_frontmatter(src, {}, remove=("protokoll_termin",))
    with contextlib.redirect_stdout(sys.stderr):
        ea.done(str(src), notes=f"Protokoll in [[{Path(note).stem}]] übernommen", typ=ABLAGE)
    return res


# ------------------------------------------------------------------ Rueckfrage

def rueckfrage(src: Path, art_: str, tag: str, name: str, kandidaten: list[dict], *, dry_run: bool = False) -> str:
    import rueckfragen as rf
    opts = []
    for i, k in enumerate(kandidaten):
        if k.get("note"):
            opts.append(f"{chr(65 + i)}) [[{Path(k['note']).stem}]]")
        else:
            opts.append(f"{chr(65 + i)}) Kalender: {k['titel']}" + (f" ({k['zeit']})" if k["zeit"] else "")
                        + " – Notiz anlegen")
    n = len(kandidaten)
    if tag:
        opts.append(f"{chr(65 + n)}) Neue Termin-Notiz „{name}“ am {tag}")
        n += 1
    opts.append(f"{chr(65 + n)}) Kein Termin – normal einarbeiten")
    kontext = (f"Im Eingang liegt {ART[art_]}: „{src.name}“"
               + (f" vom {tag}" if tag else " ohne erkennbares Datum")
               + ". Zu welchem Termin gehört es? Ein anderer Termin: in die Zeile schreiben, "
                 "z. B. „[[Termin-Notiz]]“.")
    if dry_run:
        return ""
    with contextlib.redirect_stdout(sys.stderr):
        cid = rf.add_clarification(f"Protokoll zuordnen: {name}", kontext, opts, source_file=src.stem)
    rf.save_pending(cid, {"kind": RUECKFRAGE, "quelle": _rel(src), "art": art_, "tag": tag, "titel": name,
                          "kandidaten": [{"note": _rel(k["note"])} if k.get("note") else {"event": k["event"]}
                                         for k in kandidaten]})
    vp.update_frontmatter(src, {"deferred": True, "defer_reason": "Protokoll: Termin unklar – Rückfrage",
                                "protokoll_termin": cid})
    return cid


def _notiz(stem: str) -> Path | None:
    for root in tk.meeting_roots():
        for f in root.rglob(f"{stem}.md") if root.is_dir() else []:
            return f
    return None


def antwort(cid: str, data: dict, choice: str, *, dry_run: bool = False) -> dict:
    """Angehakte Rueckfrage: Termin aus der Liste, eine eingetragene [[Termin-Notiz]], eine neue
    Termin-Notiz - oder "kein Termin" (dann arbeitet das Einarbeiten die Datei normal ein)."""
    import rueckfragen as rf
    src = vp.VAULT / str(data.get("quelle") or "")
    if not src.is_file():
        if not dry_run:
            (rf.PENDING_DIR / f"{cid}.json").unlink(missing_ok=True)
            rf.resolve_clarification(cid, "Datei liegt nicht mehr im Eingang – nichts zu tun")
        return {"id": cid, "ok": True, "auswahl": choice, "ergebnis": "Datei nicht mehr im Eingang"}
    low = choice.lower()
    kand = data.get("kandidaten") or []
    m = re.match(r"\s*([A-Z])\)", choice)
    idx = ord(m.group(1)) - 65 if m else -1
    link = re.search(r"\[\[([^\]|#]+)", choice)
    ziel = None
    if "kein termin" in low:
        if not dry_run:
            vp.update_frontmatter(src, {"protokoll": "kein_termin"},
                                  remove=("deferred", "defer_reason", "protokoll_termin"))
            (rf.PENDING_DIR / f"{cid}.json").unlink(missing_ok=True)
            rf.resolve_clarification(cid, f"Haken „{choice[:60]}“ – kein Termin, wird normal eingearbeitet")
        return {"id": cid, "ok": True, "auswahl": choice, "ergebnis": "kein Termin – normales Einarbeiten"}
    if 0 <= idx < len(kand) and not (link and kand[idx].get("note")
                                     and Path(kand[idx]["note"]).stem != link.group(1).strip()):
        k = kand[idx]
        ziel = {"note": vp.VAULT / k["note"]} if k.get("note") else {"event": k["event"]}
    elif link:
        note = _notiz(link.group(1).strip())
        ziel = {"note": note} if note else None
    elif "neue termin-notiz" in low and data.get("tag"):
        ziel = {"event": {"date": data["tag"], "time": "", "title": data.get("titel") or src.stem}}
    if not ziel or (ziel.get("note") is not None and not Path(ziel["note"]).is_file()):
        return {"id": cid, "ok": False, "auswahl": choice,
                "grund": "Termin nicht gefunden – „[[Termin-Notiz]]“ in die Zeile schreiben"}
    fm = vp.read_frontmatter(src)
    body = vp.split_frontmatter(src.read_text(encoding="utf-8"))[1]
    if not dry_run:
        vp.update_frontmatter(src, {}, remove=("deferred", "defer_reason"))
    r = uebernehmen(src, fm, body, str(data.get("art") or "protokoll"), ziel, dry_run=dry_run)
    if not dry_run:
        (rf.PENDING_DIR / f"{cid}.json").unlink(missing_ok=True)
        rf.resolve_clarification(cid, f"Haken „{choice[:60]}“ – Protokoll in [[{r['notiz']}]]")
    return {"id": cid, "ok": True, "auswahl": choice, "ergebnis": f"in {r['notiz']}"}


# ------------------------------------------------------------------ Lauf

def run(*, dry_run: bool = False) -> dict:
    import arbeitspaket
    rep: dict = {"zugeordnet": [], "rueckfragen": [], "ohne_termin": []}
    for f, suffix in arbeitspaket.listing():
        if suffix != ".md":
            continue
        fm = vp.read_frontmatter(f)
        if (mp.is_processed(fm) or fm.get("deferred") or fm.get("protokoll") == "kein_termin"
                or fm.get("protokoll_termin")):
            continue
        body = vp.split_frontmatter(f.read_text(encoding="utf-8"))[1]
        a = art(fm, body)
        if not a:
            continue
        tag, name = datum(f, fm, body), titel(f, fm, body)
        stark = a in ("transkript", "teams")          # sicher ein Termin-Material
        ziel, kandidaten = entscheiden(termine(tag), name, alle_zeigen=stark) if tag else (None, [])
        if ziel:
            rep["zugeordnet"].append(uebernehmen(f, fm, body, a, ziel, dry_run=dry_run))
        elif kandidaten or stark:
            rep["rueckfragen"].append({"datei": f.name, "art": a,
                                       "id": rueckfrage(f, a, tag, name, kandidaten, dry_run=dry_run)})
        else:
            rep["ohne_termin"].append(f.name)
    return rep


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Protokolle im Eingang ihrem Termin zuordnen")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args(argv)
    rep = run(dry_run=a.dry_run)
    if a.json:
        print(json.dumps(rep, ensure_ascii=False, indent=1))
        return 0
    for r in rep["zugeordnet"]:
        print(f"[ZUGEORDNET] {r['datei']} -> {r['notiz']} ({ABSCHNITT[r['art']]})")
    for r in rep["rueckfragen"]:
        print(f"[RUECKFRAGE] {r['datei']} ({r['id'] or 'Probelauf'})")
    for n in rep["ohne_termin"]:
        print(f"[OHNE TERMIN] {n} - bleibt fuer das Einarbeiten")
    if not any(rep.values()):
        print("Keine Protokolle im Eingang.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
